/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */
#ifndef MONNAND_GTKTAGAL_ADD_TAGS_TO_FILE_WND_IF_H
#define MONNAND_GTKTAGAL_ADD_TAGS_TO_FILE_WND_IF_H

#include <gtk/gtk.h>
#include "tagal.h"

typedef struct add_tags_to_file_wnd_arg_t {
	GtkWidget *wnd;
	GtkEntry *input_entry;
	GtkLabel *status_label;
	GtkTreeView *tags_tree;
	gchar *file_path;
	tagal_t *tagal;
} add_tags_to_file_wnd_arg_t;

GtkWidget* create_add_tags_to_file_wnd (add_tags_to_file_wnd_arg_t *arg);

#endif /* MONNAND_GTKTAGAL_ADD_TAGS_TO_FILE_WND_IF_H */
