/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"
#include "tags_list.h"
#include "tags_list_view.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_add_tags_to_file_wnd (add_tags_to_file_wnd_arg_t *arg)
{
  GtkWidget *add_tags_to_file_wnd;
  GtkWidget *vpaned1;
  GtkWidget *hpaned3;
  GtkWidget *vbox4;
  GtkWidget *add_tags_to_file_entry;
  GtkWidget *add_tags_to_file_label;
  GtkWidget *toolbar3;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *tmp_image;
  GtkWidget *add_tags_to_file_confirm;
  GtkWidget *add_tags_to_file_cancel;
  GtkWidget *expander1;
  GtkWidget *scrolledwindow3;
  GtkWidget *add_tags_to_file_tags_tree;
  GtkWidget *label3;

  add_tags_to_file_wnd = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_events (add_tags_to_file_wnd, GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK);
  gtk_window_set_title (GTK_WINDOW (add_tags_to_file_wnd), arg->file_path);
  gtk_window_set_default_size (GTK_WINDOW (add_tags_to_file_wnd), 446, 100);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (add_tags_to_file_wnd), TRUE);
  gtk_window_set_skip_taskbar_hint (GTK_WINDOW (add_tags_to_file_wnd), TRUE);
  gtk_window_set_skip_pager_hint (GTK_WINDOW (add_tags_to_file_wnd), TRUE);

  vpaned1 = gtk_vpaned_new ();
  gtk_widget_show (vpaned1);
  gtk_container_add (GTK_CONTAINER (add_tags_to_file_wnd), vpaned1);
  gtk_paned_set_position (GTK_PANED (vpaned1), 70);

  hpaned3 = gtk_hpaned_new ();
  gtk_widget_show (hpaned3);
  gtk_paned_pack1 (GTK_PANED (vpaned1), hpaned3, FALSE, TRUE);
  gtk_paned_set_position (GTK_PANED (hpaned3), 313);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_paned_pack1 (GTK_PANED (hpaned3), vbox4, FALSE, TRUE);

  add_tags_to_file_entry = gtk_entry_new ();
  gtk_widget_show (add_tags_to_file_entry);
  gtk_box_pack_start (GTK_BOX (vbox4), add_tags_to_file_entry, TRUE, TRUE, 0);
  gtk_widget_set_events (add_tags_to_file_entry, GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK);
  gtk_entry_set_invisible_char (GTK_ENTRY (add_tags_to_file_entry), 9679);
  gtk_entry_set_activates_default (GTK_ENTRY (add_tags_to_file_entry), TRUE);

  add_tags_to_file_label = gtk_label_new ("");
  gtk_widget_show (add_tags_to_file_label);
  gtk_box_pack_start (GTK_BOX (vbox4), add_tags_to_file_label, TRUE, TRUE, 0);

  toolbar3 = gtk_toolbar_new ();
  gtk_widget_show (toolbar3);
  gtk_paned_pack2 (GTK_PANED (hpaned3), toolbar3, TRUE, TRUE);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar3), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar3));

  tmp_image = gtk_image_new_from_stock ("gtk-ok", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  add_tags_to_file_confirm = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Add"));
  gtk_widget_show (add_tags_to_file_confirm);
  gtk_container_add (GTK_CONTAINER (toolbar3), add_tags_to_file_confirm);

  tmp_image = gtk_image_new_from_stock ("gtk-cancel", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  add_tags_to_file_cancel = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Cancel"));
  gtk_widget_show (add_tags_to_file_cancel);
  gtk_container_add (GTK_CONTAINER (toolbar3), add_tags_to_file_cancel);

  expander1 = gtk_expander_new (NULL);
  gtk_widget_show (expander1);
  gtk_paned_pack2 (GTK_PANED (vpaned1), expander1, TRUE, TRUE);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_container_add (GTK_CONTAINER (expander1), scrolledwindow3);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  add_tags_to_file_tags_tree = gtk_tree_view_new ();
  set_tags_list_view(GTK_TREE_VIEW(add_tags_to_file_tags_tree));
  refresh_tags_tree_by_path(gtk_tree_view_get_model(
	GTK_TREE_VIEW(add_tags_to_file_tags_tree)), arg->tagal, "");

  gtk_widget_show (add_tags_to_file_tags_tree);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), add_tags_to_file_tags_tree);
  gtk_widget_set_events (add_tags_to_file_tags_tree, GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK);

  label3 = gtk_label_new (_("Show Tags"));
  gtk_widget_show (label3);
  gtk_expander_set_label_widget (GTK_EXPANDER (expander1), label3);

  arg->input_entry = GTK_ENTRY(add_tags_to_file_entry);
  arg->status_label = GTK_LABEL(add_tags_to_file_label);
  arg->tags_tree = GTK_TREE_VIEW(add_tags_to_file_tags_tree);
  arg->wnd = add_tags_to_file_wnd;

  g_signal_connect ((gpointer) add_tags_to_file_wnd, "delete_event",
                    G_CALLBACK (on_add_tags_to_file_wnd_delete_event),
                    arg);
  g_signal_connect ((gpointer) add_tags_to_file_confirm, "clicked",
                    G_CALLBACK (on_add_tags_to_file_confirm_clicked),
                    arg);
  g_signal_connect ((gpointer) add_tags_to_file_cancel, "clicked",
                    G_CALLBACK (on_add_tags_to_file_cancel_clicked),
                    arg);
  g_signal_connect ((gpointer) add_tags_to_file_cancel, "clicked",
                    G_CALLBACK (on_add_tags_to_file_cancel_clicked),
                    arg);
  g_signal_connect ((gpointer) add_tags_to_file_tags_tree, "button_release_event",
                    G_CALLBACK (on_add_tags_to_file_tags_tree_button_release_event),
                    arg);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (add_tags_to_file_wnd, add_tags_to_file_wnd, "add_tags_to_file_wnd");
  GLADE_HOOKUP_OBJECT (add_tags_to_file_wnd, vpaned1, "vpaned1");
  GLADE_HOOKUP_OBJECT (add_tags_to_file_wnd, hpaned3, "hpaned3");
  GLADE_HOOKUP_OBJECT (add_tags_to_file_wnd, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (add_tags_to_file_wnd, add_tags_to_file_entry, "add_tags_to_file_entry");
  GLADE_HOOKUP_OBJECT (add_tags_to_file_wnd, add_tags_to_file_label, "add_tags_to_file_label");
  GLADE_HOOKUP_OBJECT (add_tags_to_file_wnd, toolbar3, "toolbar3");
  GLADE_HOOKUP_OBJECT (add_tags_to_file_wnd, add_tags_to_file_confirm, "add_tags_to_file_confirm");
  GLADE_HOOKUP_OBJECT (add_tags_to_file_wnd, add_tags_to_file_cancel, "add_tags_to_file_cancel");
  GLADE_HOOKUP_OBJECT (add_tags_to_file_wnd, expander1, "expander1");
  GLADE_HOOKUP_OBJECT (add_tags_to_file_wnd, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (add_tags_to_file_wnd, add_tags_to_file_tags_tree, "add_tags_to_file_tags_tree");
  GLADE_HOOKUP_OBJECT (add_tags_to_file_wnd, label3, "label3");

  return add_tags_to_file_wnd;
}

