/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"
#include "global_var.h"
#include "files_list_view.h"
#include "tags_list_view.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_search_wnd (void)
{
    GtkWidget *search_wnd;
  GtkWidget *vbox1;
  GtkWidget *toolbar1;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *tmp_image;
  GtkWidget *add_file_button;
  //GtkWidget *add_tag_button;
  GtkWidget *connect_button;
  GtkWidget *disconnect_button;
  GtkWidget *toolbutton1;
  GtkWidget *config_button;
  GtkWidget *toolbutton2;
  GtkWidget *help_button;
  GtkWidget *about_button;
  GtkWidget *vpaned1;
  GtkWidget *hpaned2;
  GtkWidget *text_input_entry;
  GtkWidget *toolbar2;
  GtkWidget *search_button;
  GtkWidget *clear_button;
  GtkWidget *hpaned1;
  GtkWidget *vpaned2;
  GtkWidget *files_tree_label;
  GtkWidget *scrolledwindow1;
  GtkWidget *files_tree;
  GtkWidget *vpaned3;
  GtkWidget *tags_tree_label;
  GtkWidget *scrolledwindow2;
  GtkWidget *tags_tree;

  search_wnd = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_events (search_wnd, GDK_POINTER_MOTION_MASK 
	| GDK_POINTER_MOTION_HINT_MASK 
	| GDK_BUTTON_PRESS_MASK 
	| GDK_BUTTON_RELEASE_MASK
  	| GDK_KEY_PRESS_MASK 
	| GDK_KEY_RELEASE_MASK);
  gtk_window_set_title (GTK_WINDOW (search_wnd), _("Tagal"));
  gtk_window_set_default_size (GTK_WINDOW (search_wnd), 500, 400);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (search_wnd), vbox1);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), toolbar1, FALSE, TRUE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1));

  tmp_image = gtk_image_new_from_stock ("gtk-new", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  add_file_button = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Add File"));
  gtk_widget_show (add_file_button);
  gtk_container_add (GTK_CONTAINER (toolbar1), add_file_button);

  /*
  tmp_image = gtk_image_new_from_stock ("gtk-add", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  add_tag_button = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Add Tag"));
  gtk_widget_show (add_tag_button);
  gtk_container_add (GTK_CONTAINER (toolbar1), add_tag_button);
  */

  tmp_image = gtk_image_new_from_stock ("gtk-connect", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  connect_button = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Connect"));
  gtk_widget_show (connect_button);
  gtk_container_add (GTK_CONTAINER (toolbar1), connect_button);

  tmp_image = gtk_image_new_from_stock ("gtk-disconnect", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  disconnect_button = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Disconnect"));
  gtk_widget_show (disconnect_button);
  gtk_container_add (GTK_CONTAINER (toolbar1), disconnect_button);

  toolbutton1 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_show (toolbutton1);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton1);

  tmp_image = gtk_image_new_from_stock ("gtk-preferences", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  config_button = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Config"));
  gtk_widget_show (config_button);
  gtk_container_add (GTK_CONTAINER (toolbar1), config_button);

  toolbutton2 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_show (toolbutton2);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton2);

  tmp_image = gtk_image_new_from_stock ("gtk-help", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  help_button = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Help"));
  gtk_widget_show (help_button);
  gtk_container_add (GTK_CONTAINER (toolbar1), help_button);

  tmp_image = gtk_image_new_from_stock ("gtk-about", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  about_button = (GtkWidget*) gtk_tool_button_new (tmp_image, _("About"));
  gtk_widget_show (about_button);
  gtk_container_add (GTK_CONTAINER (toolbar1), about_button);

  vpaned1 = gtk_vpaned_new ();
  gtk_widget_show (vpaned1);
  gtk_box_pack_start (GTK_BOX (vbox1), vpaned1, TRUE, TRUE, 0);
  gtk_paned_set_position (GTK_PANED (vpaned1), 54);

  hpaned2 = gtk_hpaned_new ();
  gtk_widget_show (hpaned2);
  gtk_paned_pack1 (GTK_PANED (vpaned1), hpaned2, FALSE, TRUE);
  gtk_paned_set_position (GTK_PANED (hpaned2), 346);

  text_input_entry = gtk_entry_new ();
  gtk_widget_show (text_input_entry);
  gtk_paned_pack1 (GTK_PANED (hpaned2), text_input_entry, FALSE, TRUE);
  gtk_widget_set_events (text_input_entry, GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK);
  gtk_entry_set_invisible_char (GTK_ENTRY (text_input_entry), 9679);
  gtk_entry_set_activates_default (GTK_ENTRY (text_input_entry), TRUE);

  toolbar2 = gtk_toolbar_new ();
  gtk_widget_show (toolbar2);
  gtk_paned_pack2 (GTK_PANED (hpaned2), toolbar2, TRUE, TRUE);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar2), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar2));

  tmp_image = gtk_image_new_from_stock ("gtk-find", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  search_button = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Search"));
  gtk_widget_show (search_button);
  gtk_container_add (GTK_CONTAINER (toolbar2), search_button);

  tmp_image = gtk_image_new_from_stock ("gtk-clear", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  clear_button = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Clear"));
  gtk_widget_show (clear_button);
  gtk_container_add (GTK_CONTAINER (toolbar2), clear_button);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_show (hpaned1);
  gtk_paned_pack2 (GTK_PANED (vpaned1), hpaned1, TRUE, TRUE);
  gtk_paned_set_position (GTK_PANED (hpaned1), 260);

  vpaned2 = gtk_vpaned_new ();
  gtk_widget_show (vpaned2);
  gtk_paned_pack1 (GTK_PANED (hpaned1), vpaned2, FALSE, TRUE);
  gtk_paned_set_position (GTK_PANED (vpaned2), 28);

  files_tree_label = gtk_label_new (_("All Files"));
  gtk_widget_show (files_tree_label);
  gtk_paned_pack1 (GTK_PANED (vpaned2), files_tree_label, FALSE, TRUE);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_paned_pack2 (GTK_PANED (vpaned2), scrolledwindow1, TRUE, TRUE);

  files_tree = gtk_tree_view_new ();
  gtk_widget_show (files_tree);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), files_tree);
  gtk_widget_set_events (files_tree, GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK);
  gtk_tree_view_set_reorderable (GTK_TREE_VIEW (files_tree), TRUE);

  vpaned3 = gtk_vpaned_new ();
  gtk_widget_show (vpaned3);
  gtk_paned_pack2 (GTK_PANED (hpaned1), vpaned3, TRUE, TRUE);
  gtk_paned_set_position (GTK_PANED (vpaned3), 28);

  tags_tree_label = gtk_label_new (_("All Tags"));
  gtk_widget_show (tags_tree_label);
  gtk_paned_pack1 (GTK_PANED (vpaned3), tags_tree_label, FALSE, TRUE);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_paned_pack2 (GTK_PANED (vpaned3), scrolledwindow2, TRUE, TRUE);

  tags_tree = gtk_tree_view_new ();
  gtk_widget_show (tags_tree);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), tags_tree);
  gtk_widget_set_events (tags_tree, GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK);
  gtk_tree_view_set_reorderable (GTK_TREE_VIEW (tags_tree), TRUE);

  /* monnand changed start: */
  set_files_list_view(GTK_TREE_VIEW(files_tree));
  set_tags_list_view(GTK_TREE_VIEW(tags_tree));
  search_main_wnd_arg.files_tree = GTK_TREE_VIEW(files_tree);
  search_main_wnd_arg.tags_tree = GTK_TREE_VIEW(tags_tree);
  search_main_wnd_arg.input_text_entry = GTK_ENTRY(text_input_entry);
  search_main_wnd_arg.files_tree_label = GTK_LABEL(files_tree_label);
  search_main_wnd_arg.tags_tree_label = GTK_LABEL(tags_tree_label);

  gtk_entry_set_text(GTK_ENTRY(text_input_entry), _("Input tags"));
  gtk_editable_select_region(GTK_EDITABLE(text_input_entry), 0, -1);

  g_signal_connect ((gpointer) search_wnd, "delete-event",
		  G_CALLBACK (on_search_wnd_delete_event),
		  &search_main_wnd_arg);

  g_signal_connect ((gpointer) add_file_button, "clicked",
                    G_CALLBACK (on_add_file_button_clicked),
                    &search_main_wnd_arg);
  /*
  g_signal_connect ((gpointer) add_tag_button, "clicked",
                    G_CALLBACK (on_add_tag_button_clicked),
                    &search_main_wnd_arg);
  */
  g_signal_connect ((gpointer) connect_button, "clicked",
                    G_CALLBACK (on_connect_button_clicked),
                    &search_main_wnd_arg);
  g_signal_connect ((gpointer) disconnect_button, "clicked",
                    G_CALLBACK (on_disconnect_button_clicked),
                    &search_main_wnd_arg);
  g_signal_connect ((gpointer) config_button, "clicked",
                    G_CALLBACK (on_config_button_clicked),
                    &search_main_wnd_arg);
  g_signal_connect ((gpointer) help_button, "clicked",
                    G_CALLBACK (on_help_button_clicked),
                    &search_main_wnd_arg);
  g_signal_connect ((gpointer) about_button, "clicked",
                    G_CALLBACK (on_about_button_clicked),
                    &search_main_wnd_arg);
  g_signal_connect ((gpointer) search_button, "clicked",
                    G_CALLBACK (on_search_button_clicked),
                    &search_main_wnd_arg);
  g_signal_connect ((gpointer) clear_button, "clicked",
                    G_CALLBACK (on_clear_button_clicked),
                    &search_main_wnd_arg);
  g_signal_connect ((gpointer) files_tree, "select_cursor_row",
                    G_CALLBACK (on_files_tree_select_cursor_row),
                    &search_main_wnd_arg);
  g_signal_connect ((gpointer) files_tree, "key_press_event",
                    G_CALLBACK (on_files_tree_key_press_event),
                    &search_main_wnd_arg);
  g_signal_connect ((gpointer) files_tree, "row_activated",
                    G_CALLBACK (on_files_tree_row_activated),
                    &search_main_wnd_arg);
  g_signal_connect ((gpointer) files_tree, "button_release_event",
                    G_CALLBACK (on_files_tree_button_release_event),
                    &search_main_wnd_arg);
  g_signal_connect ((gpointer) files_tree, "key_release_event",
                    G_CALLBACK (on_files_tree_key_release_event),
                    &search_main_wnd_arg);
  g_signal_connect ((gpointer) tags_tree, "select_cursor_row",
                    G_CALLBACK (on_tags_tree_select_cursor_row),
                    &search_main_wnd_arg);
  g_signal_connect ((gpointer) tags_tree, "key_press_event",
                    G_CALLBACK (on_tags_tree_key_press_event),
                    &search_main_wnd_arg);
  g_signal_connect ((gpointer) tags_tree, "row_activated",
                    G_CALLBACK (on_tags_tree_row_activated),
                    &search_main_wnd_arg);
  g_signal_connect ((gpointer) tags_tree, "button_release_event",
                    G_CALLBACK (on_tags_tree_button_release_event),
                    &search_main_wnd_arg);
  g_signal_connect ((gpointer) tags_tree, "key_release_event",
                    G_CALLBACK (on_tags_tree_key_release_event),
                    &search_main_wnd_arg);
  /* monnand changed end */

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (search_wnd, search_wnd, "search_wnd");
  GLADE_HOOKUP_OBJECT (search_wnd, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (search_wnd, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (search_wnd, add_file_button, "add_file_button");
//  GLADE_HOOKUP_OBJECT (search_wnd, add_tag_button, "add_tag_button");
  GLADE_HOOKUP_OBJECT (search_wnd, connect_button, "connect_button");
  GLADE_HOOKUP_OBJECT (search_wnd, disconnect_button, "disconnect_button");
  GLADE_HOOKUP_OBJECT (search_wnd, toolbutton1, "toolbutton1");
  GLADE_HOOKUP_OBJECT (search_wnd, config_button, "config_button");
  GLADE_HOOKUP_OBJECT (search_wnd, toolbutton2, "toolbutton2");
  GLADE_HOOKUP_OBJECT (search_wnd, help_button, "help_button");
  GLADE_HOOKUP_OBJECT (search_wnd, about_button, "about_button");
  GLADE_HOOKUP_OBJECT (search_wnd, vpaned1, "vpaned1");
  GLADE_HOOKUP_OBJECT (search_wnd, hpaned2, "hpaned2");
  GLADE_HOOKUP_OBJECT (search_wnd, text_input_entry, "text_input_entry");
  GLADE_HOOKUP_OBJECT (search_wnd, toolbar2, "toolbar2");
  GLADE_HOOKUP_OBJECT (search_wnd, search_button, "search_button");
  GLADE_HOOKUP_OBJECT (search_wnd, clear_button, "clear_button");
  GLADE_HOOKUP_OBJECT (search_wnd, hpaned1, "hpaned1");
  GLADE_HOOKUP_OBJECT (search_wnd, vpaned2, "vpaned2");
  GLADE_HOOKUP_OBJECT (search_wnd, files_tree_label, "files_tree_label");
  GLADE_HOOKUP_OBJECT (search_wnd, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (search_wnd, files_tree, "files_tree");
  GLADE_HOOKUP_OBJECT (search_wnd, vpaned3, "vpaned3");
  GLADE_HOOKUP_OBJECT (search_wnd, tags_tree_label, "tags_tree_label");
  GLADE_HOOKUP_OBJECT (search_wnd, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (search_wnd, tags_tree, "tags_tree");


  return search_wnd;
}

/* monnand change start: */
GtkWidget*
create_file_item_menu (main_wnd_menu_arg_t *arg)
/* monnand change end --- add a parameter */
{
  GtkWidget *file_item_menu;
  GtkWidget *open_file;
  GtkWidget *menu_item_image2;
  GtkWidget *copy_file_path;
  GtkWidget *menu_item_image9;
  GtkWidget *add_tags_to_file;
  GtkWidget *menu_item_image8;
  GtkWidget *file_open_dir;
  GtkWidget *img_open_dir;
  //GtkWidget *file_show_tags;
  //GtkWidget *menu_item_image6;
  //GtkWidget *file_details;
  //GtkWidget *menu_item_image1;
  GtkWidget *del_file;
  GtkWidget *menu_item_image3;

  file_item_menu = gtk_menu_new ();
  gtk_widget_set_events (file_item_menu, GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK);

  file_open_dir = gtk_image_menu_item_new_with_mnemonic (_("Open Directory"));
  gtk_widget_show (file_open_dir);
  gtk_container_add (GTK_CONTAINER (file_item_menu), file_open_dir);

  img_open_dir = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (file_open_dir), img_open_dir);

  open_file = gtk_image_menu_item_new_with_mnemonic (_("Open File"));
  gtk_widget_show (open_file);
  gtk_container_add (GTK_CONTAINER (file_item_menu), open_file);

  menu_item_image2 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (open_file), menu_item_image2);

  copy_file_path = gtk_image_menu_item_new_with_mnemonic (_("Copy Path"));
  gtk_widget_show (copy_file_path);
  gtk_container_add (GTK_CONTAINER (file_item_menu), copy_file_path);

  menu_item_image9 = gtk_image_new_from_stock ("gtk-copy", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (menu_item_image9);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (copy_file_path), menu_item_image9);
  add_tags_to_file = gtk_image_menu_item_new_with_mnemonic (_("Add Tags"));
  gtk_widget_show (add_tags_to_file);
  gtk_container_add (GTK_CONTAINER (file_item_menu), add_tags_to_file);

  menu_item_image8 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (menu_item_image8);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (add_tags_to_file), menu_item_image8);

  /*
  file_show_tags = gtk_image_menu_item_new_with_mnemonic (_("Tags"));
  gtk_widget_show (file_show_tags);
  gtk_container_add (GTK_CONTAINER (file_item_menu), file_show_tags);

  menu_item_image6 = gtk_image_new_from_stock ("gtk-index", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (menu_item_image6);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (file_show_tags), menu_item_image6);

  file_details = gtk_image_menu_item_new_with_mnemonic (_("Details"));
  gtk_widget_show (file_details);
  gtk_container_add (GTK_CONTAINER (file_item_menu), file_details);

  menu_item_image1 = gtk_image_new_from_stock ("gtk-properties", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (menu_item_image1);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (file_details), menu_item_image1);
  */

  del_file = gtk_image_menu_item_new_with_mnemonic (_("Delete"));
  gtk_widget_show (del_file);
  gtk_container_add (GTK_CONTAINER (file_item_menu), del_file);

  menu_item_image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (del_file), menu_item_image3);

/* monnand change start: */
  g_signal_connect ((gpointer) file_item_menu, "selection-done",
                    G_CALLBACK (menu_reaper),
		    arg);
  g_signal_connect ((gpointer) file_open_dir, "activate",
                    G_CALLBACK (on_file_open_dir_activate),
		    arg);
  g_signal_connect ((gpointer) open_file, "activate",
                    G_CALLBACK (on_open_file_activate),
		    arg);
  g_signal_connect ((gpointer) copy_file_path, "activate",
                    G_CALLBACK (on_copy_file_path_activate),
		    arg);
  g_signal_connect ((gpointer) add_tags_to_file, "activate",
                    G_CALLBACK (on_add_tags_to_file_activate),
		    arg);
  /*
  g_signal_connect ((gpointer) file_show_tags, "activate",
                    G_CALLBACK (on_file_show_tags_activate),
		    arg);
  g_signal_connect ((gpointer) file_details, "activate",
                    G_CALLBACK (on_file_details_activate),
		    arg);
  */
  g_signal_connect ((gpointer) del_file, "activate",
                    G_CALLBACK (on_del_file_activate),
		    arg);
/* monnand change end --- change the 4th parameter as the given one */

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (file_item_menu, file_item_menu, "file_item_menu");
  GLADE_HOOKUP_OBJECT (file_item_menu, open_file, "open_file");
  GLADE_HOOKUP_OBJECT (file_item_menu, file_open_dir, "file_open_dir");
  GLADE_HOOKUP_OBJECT (file_item_menu, img_open_dir, "img_open_dir");
  GLADE_HOOKUP_OBJECT (file_item_menu, menu_item_image2, "menu_item_image2");
  GLADE_HOOKUP_OBJECT (file_item_menu, copy_file_path, "copy_file_path");
  GLADE_HOOKUP_OBJECT (file_item_menu, menu_item_image9, "menu_item_image9");
  GLADE_HOOKUP_OBJECT (file_item_menu, add_tags_to_file, "add_tags_to_file");
  GLADE_HOOKUP_OBJECT (file_item_menu, menu_item_image8, "menu_item_image8");
  /*
  GLADE_HOOKUP_OBJECT (file_item_menu, file_show_tags, "file_show_tags");
  GLADE_HOOKUP_OBJECT (file_item_menu, menu_item_image6, "menu_item_image6");
  GLADE_HOOKUP_OBJECT (file_item_menu, file_details, "file_details");
  GLADE_HOOKUP_OBJECT (file_item_menu, menu_item_image1, "menu_item_image1");
  */
  GLADE_HOOKUP_OBJECT (file_item_menu, del_file, "del_file");
  GLADE_HOOKUP_OBJECT (file_item_menu, menu_item_image3, "menu_item_image3");

  return file_item_menu;
}

GtkWidget*
create_tag_item_menu (main_wnd_menu_arg_t *arg)
{
  GtkWidget *tag_item_menu;
  GtkWidget *copy_tag;
  GtkWidget *menu_item_image4;
/*
  GtkWidget *tag_search;
  GtkWidget *menu_item_image4;
  GtkWidget *add_files_to_tag;
  GtkWidget *menu_item_image7;
  */
  GtkWidget *tag_del;
  GtkWidget *menu_item_image5;

  tag_item_menu = gtk_menu_new ();
  gtk_widget_set_events (tag_item_menu, GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK);

  copy_tag = gtk_image_menu_item_new_with_mnemonic (_("Copy Tag"));
  gtk_widget_show (copy_tag);
  gtk_container_add (GTK_CONTAINER (tag_item_menu), copy_tag);

  menu_item_image4 = gtk_image_new_from_stock ("gtk-copy", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (menu_item_image4);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (copy_tag), menu_item_image4);

  /*
  tag_search = gtk_image_menu_item_new_with_mnemonic (_("Search"));
  gtk_widget_show (tag_search);
  gtk_container_add (GTK_CONTAINER (tag_item_menu), tag_search);

  menu_item_image4 = gtk_image_new_from_stock ("gtk-index", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (menu_item_image4);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (tag_search), menu_item_image4);

  add_files_to_tag = gtk_image_menu_item_new_with_mnemonic (_("Add Files"));
  gtk_widget_show (add_files_to_tag);
  gtk_container_add (GTK_CONTAINER (tag_item_menu), add_files_to_tag);

  menu_item_image7 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (menu_item_image7);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (add_files_to_tag), menu_item_image7);
  */

  tag_del = gtk_image_menu_item_new_with_mnemonic (_("Delete"));
  gtk_widget_show (tag_del);
  gtk_container_add (GTK_CONTAINER (tag_item_menu), tag_del);

  menu_item_image5 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (menu_item_image5);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (tag_del), menu_item_image5);

  /* monnand change start: */
  g_signal_connect ((gpointer) tag_item_menu, "selection-done",
                    G_CALLBACK (menu_reaper),
		    arg);
  g_signal_connect ((gpointer) copy_tag, "activate",
                    G_CALLBACK (on_copy_tag_activate),
		    arg);
  /*
  g_signal_connect ((gpointer) tag_search, "activate",
                    G_CALLBACK (on_tag_search_activate),
		    arg);
  g_signal_connect ((gpointer) add_files_to_tag, "activate",
                    G_CALLBACK (on_add_files_to_tag_activate),
		    arg);
  */
  g_signal_connect ((gpointer) tag_del, "activate",
                    G_CALLBACK (on_tag_del_activate),
		    arg);
  /* monnand change end --- change the last parameter */

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (tag_item_menu, tag_item_menu, "tag_item_menu");
  GLADE_HOOKUP_OBJECT (tag_item_menu, copy_tag, "copy_tag");
  GLADE_HOOKUP_OBJECT (tag_item_menu, menu_item_image4, "menu_item_image4");
  /*
  GLADE_HOOKUP_OBJECT (tag_item_menu, tag_search, "tag_search");
  GLADE_HOOKUP_OBJECT (tag_item_menu, menu_item_image4, "menu_item_image4");
  GLADE_HOOKUP_OBJECT (tag_item_menu, add_files_to_tag, "add_files_to_tag");
  GLADE_HOOKUP_OBJECT (tag_item_menu, menu_item_image7, "menu_item_image7");
  */
  GLADE_HOOKUP_OBJECT (tag_item_menu, tag_del, "tag_del");
  GLADE_HOOKUP_OBJECT (tag_item_menu, menu_item_image5, "menu_item_image5");

  return tag_item_menu;
}

GtkWidget*
create_tagal_about_dialog (void)
{
  GtkWidget *tagal_about_dialog;
  const gchar *authors[] = {
    "Monnand <monnand@gmail.com>",
    NULL
  };
  /* TRANSLATORS: Replace this string with your names, one name per line. */
  gchar *translators = _("translator-credits");
  GtkWidget *dialog_vbox1;

  tagal_about_dialog = gtk_about_dialog_new ();
  gtk_container_set_border_width (GTK_CONTAINER (tagal_about_dialog), 5);
  gtk_widget_set_events (tagal_about_dialog, GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK);
  gtk_about_dialog_set_version (GTK_ABOUT_DIALOG (tagal_about_dialog), VERSION);
  gtk_about_dialog_set_name (GTK_ABOUT_DIALOG (tagal_about_dialog), _("Tagal"));
  gtk_about_dialog_set_copyright (GTK_ABOUT_DIALOG (tagal_about_dialog), _("Copyright (c) 2008 Deng Nan."));
  gtk_about_dialog_set_comments (GTK_ABOUT_DIALOG (tagal_about_dialog), _("A little tool used to tag your files."));
  gtk_about_dialog_set_license (GTK_ABOUT_DIALOG (tagal_about_dialog), _("Tagal is free software: you can redistribute it and/or modify\nit under the terms of the GNU General Public License as published by\nthe Free Software Foundation, either version 3 of the License, or\n(at your option) any later version.\nTagal is distributed in the hope that it will be useful,\nbut WITHOUT ANY WARRANTY; without even the implied warranty of\nMERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\nGNU General Public License for more details.\nYou should have received a copy of the GNU General Public License\nalong with this program.  If not, see <http://www.gnu.org/licenses/>."));
  gtk_about_dialog_set_wrap_license (GTK_ABOUT_DIALOG (tagal_about_dialog), TRUE);
  gtk_about_dialog_set_authors (GTK_ABOUT_DIALOG (tagal_about_dialog), authors);
  gtk_about_dialog_set_translator_credits (GTK_ABOUT_DIALOG (tagal_about_dialog), translators);

  dialog_vbox1 = gtk_vbox_new (FALSE, 2);
  gtk_widget_show (dialog_vbox1);
  gtk_container_add (GTK_CONTAINER (tagal_about_dialog), dialog_vbox1);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (tagal_about_dialog, tagal_about_dialog, "tagal_about_dialog");
  GLADE_HOOKUP_OBJECT (tagal_about_dialog, dialog_vbox1, "dialog_vbox1");

  return tagal_about_dialog;
}


